# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py   # path to your conf.py

python:
  install:
    - requirements: docs/requirements.txt  # doc deps (sphinx, theme, myst-nb, etc.)
    - method: pip
      path: .                              # install your package (pip install . or -e .)

formats:
  - html

